vectordb_config: 
  chroma:
    embedding: 
      openAI:
        model_name: "text-embedding-3-small"
ingestion_config:
  pdf:
    splitter: 
      recursiveCharacterTextSplitter:
        chunk_size: 500
        chunk_overlap: 0