vectordb_config: 
  chroma:
    embedding: 
      openAI:
        model_name: "text-embedding-3-small"
ingestion_config:
  pdf:
    splitter: 
      recursiveCharacterTextSplitter:
        chunk_size: 1000
        chunk_overlap: 0
retrieval_config:
  vectorstore:
    search_type: "mmr"
    search_config:
      k: 3
      score_threshold: 0.5