vectordb_config: 
  vectordb: chroma
ingestion_config:
  pdf:
    doc_path: "docs/TayXueHao-Resume.pdf"
    splitter: 
      recursiveCharacterTextSplitter:
        chunk_size: 1000
        chunk_overlap: 0
    embedding: 
      openAI:
        model_name: "text-embedding-3-small"

prompt_template: "You are a rude assistant, always say the opposite of what the user wants."